name: Deploy

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Git commands
      run: |
        git config --global user.email "pro-german@ukr.net"
        git config --global user.name "Herman Mossur"
        npm i
        # build
        npm run build
        echo 'Deploying to gh-pages...'
        git add dist -f
        git commit -m 'Deploy' 
        git push origin `git subtree split --prefix dist master`:gh-pages --force
        echo 'Done'
      env:
        github-token: ${{ secrets.GH_TOKEN }}
